# Default site metadata (users override these in their own _config.yml)
name: "Focus Jekyll Theme"
description: "A minimalistic and elegant Jekyll theme."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "demowebsite"
email: "contact@example.com"

# Include directories if the theme relies on them, or let user decide
# include: ["_pages"]  # Typically removed or documented for user to add

permalink: /:title/

# Plugins recommended or required by the theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "author_name"
      avatar: "/assets/images/default-avatar.jpg"

  - scope:
      path: "_pages"
    values:
      layout: "page"

# Syntax and markdown
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude files not needed
exclude:
  - README.markdown
  - package.json
  - node_modules
